### ISSUE TITLE
Error: Quellübergreifende (Cross-Origin) Anfrage blockiert

### ISSUE THREAD

**Issue by reginafaller** [JirkaDellOro/EIA2-Inverted#196]
Wenn ich eine Anfrage an meinen Server sende und versuche etwas in meine Datenbank einzutragen bekomme ich den Error: "Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://fallerr.herokuapp.com/? (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt)". Auch auf den Screenshots zu sehen. 
Doch in meiner respond Funktion füge ich den header hinzu. Ich weiß nicht, was in meiner server.ts nicht stimmt. 

Link zu meinem Repository: https://github.com/reginafaller/EIA2

<img width="1012" alt="Screenshot 2020-07-26 at 21 03 58" src="https://user-images.githubusercontent.com/44026417/88487328-6b3cc980-cf84-11ea-81c3-6c0a4f287bce.png">

Das steht in meinen Heroku Logs:

<img width="1209" alt="Screenshot 2020-07-26 at 21 03 29" src="https://user-images.githubusercontent.com/44026417/88487326-6710ac00-cf84-11ea-8cbd-349159702b91.png">

<img width="1230" alt="Screenshot 2020-07-24 at 17 19 20" src="https://user-images.githubusercontent.com/44026417/88487406-18174680-cf85-11ea-8b74-32648456749e.png">

**Comment by JirkaDellOro** [comment]
Ist der Issue noch aktuell?

**Comment by ivenios** [comment]
Ich weiß nicht, ob das hilft, aber der 'Access-Control-Allow-Origin' sollte in deiner server response Funktion so drin sein: 

`function respond(_response: Http.ServerResponse, _text: string): void {
    console.log("Preparing response: " + _text);
    _response.setHeader("Access-Control-Allow-Origin", "*");
    _response.setHeader("content-type", "text/html; charset=utf-8");
    _response.write(_text);
    _response.end();
}`

Ich habe aber das Problem, wenn ich das jetzt alles über GitHub pages laufen lasse:  Das kommt, wenn ich meinen query string an den server schicken will. Ist das eine Einstellung bei gitHub pages?
_Origin https://ivenios.github.io is not allowed by Access-Control-Allow-Origin.
XMLHttpRequest cannot load https://ios-eia2.herokuapp.com/?command=registerUser&username=JohnxxXX&password=123 due to access control checks.
https://ios-eia2.herokuapp.com/?command=registerUser&username=JohnxxXX&password=123_

 

Meine Dateien: [Click here](https://github.com/ivenios/EIA2/tree/master/01_Endabgabe_v2/2_Programm)
Mein github pages: [Click here](https://ivenios.github.io/EIA2/01_Endabgabe_v2/index.html)

**Comment by ivenios** [comment]
Meine Frage hat sich geklärt, ich hatte mich in der package.json vertippt.

**Comment by JirkaDellOro** [comment]
Schließt den Issue, wenn er durch ist, bitte
